// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuYaYqapuuSQxgPodVUOMHEERU-vjmuM4',
    appId: '1:900037600070:web:326dcd4a47e264f26efb47',
    messagingSenderId: '900037600070',
    projectId: 'flutter-todo-f330a',
    authDomain: 'flutter-todo-f330a.firebaseapp.com',
    storageBucket: 'flutter-todo-f330a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkAqlnF0fVDUm3HRt69tbMh68f09RXDLo',
    appId: '1:900037600070:android:12e8304c0dc43b426efb47',
    messagingSenderId: '900037600070',
    projectId: 'flutter-todo-f330a',
    storageBucket: 'flutter-todo-f330a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnOREKjRHYR8IbXAMgR7X-wOpW98z_nKE',
    appId: '1:900037600070:ios:d19aeea8314ff85e6efb47',
    messagingSenderId: '900037600070',
    projectId: 'flutter-todo-f330a',
    storageBucket: 'flutter-todo-f330a.firebasestorage.app',
    iosBundleId: 'com.example.chapter09Todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnOREKjRHYR8IbXAMgR7X-wOpW98z_nKE',
    appId: '1:900037600070:ios:d19aeea8314ff85e6efb47',
    messagingSenderId: '900037600070',
    projectId: 'flutter-todo-f330a',
    storageBucket: 'flutter-todo-f330a.firebasestorage.app',
    iosBundleId: 'com.example.chapter09Todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuYaYqapuuSQxgPodVUOMHEERU-vjmuM4',
    appId: '1:900037600070:web:ce78e07e299aabbd6efb47',
    messagingSenderId: '900037600070',
    projectId: 'flutter-todo-f330a',
    authDomain: 'flutter-todo-f330a.firebaseapp.com',
    storageBucket: 'flutter-todo-f330a.firebasestorage.app',
  );
}
