// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKZyOJPE7-HKUIsyRH7mrEoSDP5rAb2P8',
    appId: '1:711957694329:web:e374e66e385691b6dad1a8',
    messagingSenderId: '711957694329',
    projectId: 'chat-app-d3410',
    authDomain: 'chat-app-d3410.firebaseapp.com',
    storageBucket: 'chat-app-d3410.firebasestorage.app',
    measurementId: 'G-7R2BG8LETW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqzp7hexZYrPHPhwuw74Nx6BU6L8iiqjI',
    appId: '1:711957694329:android:edfc893534fd4914dad1a8',
    messagingSenderId: '711957694329',
    projectId: 'chat-app-d3410',
    storageBucket: 'chat-app-d3410.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3T0PmGCkqeCbHAr2PT1bvI1ufrMFU2mU',
    appId: '1:711957694329:ios:b32511d28c74e079dad1a8',
    messagingSenderId: '711957694329',
    projectId: 'chat-app-d3410',
    storageBucket: 'chat-app-d3410.firebasestorage.app',
    iosBundleId: 'com.example.chapter10Chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3T0PmGCkqeCbHAr2PT1bvI1ufrMFU2mU',
    appId: '1:711957694329:ios:b32511d28c74e079dad1a8',
    messagingSenderId: '711957694329',
    projectId: 'chat-app-d3410',
    storageBucket: 'chat-app-d3410.firebasestorage.app',
    iosBundleId: 'com.example.chapter10Chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKZyOJPE7-HKUIsyRH7mrEoSDP5rAb2P8',
    appId: '1:711957694329:web:7777bb2371f0a1f2dad1a8',
    messagingSenderId: '711957694329',
    projectId: 'chat-app-d3410',
    authDomain: 'chat-app-d3410.firebaseapp.com',
    storageBucket: 'chat-app-d3410.firebasestorage.app',
    measurementId: 'G-PG4NM56PVQ',
  );
}
